# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e547bc2225de91fcac75414ff42bb3f1672a70e104cd0309ca544f45a610218ad5afb1579c547643f7b8bb34983e249ba9b77bbb01ea4d9be4142cfc9a7a34e

test:
  secret_key_base: a4da97d075fbc916d518b24698bd94808271ca9aa80ac22404ef8a598a0998edac455d2792600ce4b727d679e1203577007d24c5027b2c3b54d5962afe282b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
